### ISSUE TITLE
Adds a separate synonym chain, whose result will not be considered for boostterm resolving

### ISSUE THREAD

**Issue by tboeghk** [shopping24/solr-bmax-queryparser#2]
For certain situations it might be handsome to have some synonyms not be considered for boostterm resolving. In the @shopping24 search appliance we use so-called sub-topics, that expand a search term like `shoe` into `sneaker,slipper` etc. For those terms, we'd like to not consider boostterms.

On the one hand, we could easily process a second synonym chain. Those results will still be 100% synonyms of the given search term but will not be considered for boostterm or penalty resolving.

**Comment by joergrathlev** [comment]
“On the one hand ...” and on the other hand?

**Comment by tboeghk** [comment]
Do something crazy funky in your boostterm chain. 

![](http://stream1.gifsoup.com/view/41522/crazy-funky-junky-hat-o.gif)

**Comment by tboeghk** [comment]
done
