### ISSUE TITLE
org.apache.solr.common.SolrException: Unknown query type 'bmax'

### ISSUE THREAD

**Issue by albix** [shopping24/solr-bmax-queryparser#3]
Hey Torsten,

My name is Satya. Sorry for reaching out to hear from Github.

I would like to use your plugin in my project. 
And I did configure in schema.xml , solrconfig.xml exactly the way you directed in ReadMe.doc.

Once I place the jar(plugin) in solr/lib folder, I restarted the solr.
I tried to access the plugin by hitting this URL:
http://localhost:8983/solr/select/?q=dog&defType=bmax
But I am getting below error
org.apache.solr.common.SolrException: Unknown query type 'bmax'

can you please give me some urls(examples like query builders) to access the plugin.

Thanks in advance

@satyababu

**Comment by satyababu** [comment]
Thanks for creating the issue and looking for the issue which I have.

Please let me know How I can achieve this problem.
And thanks for creating the plugin.

Thanks,
Satyababu

**Comment by tboeghk** [comment]
Sorry for the late answer, I'll add some examples to the project. this may take some days.

**Comment by tboeghk** [comment]
I added a simple example `schema.xml` and `solrconfig.xml` with a working bmax setup: https://github.com/shopping24/solr-bmax-queryparser/tree/master/src/test/resources/solr/collection1/conf

**Comment by albix** [comment]
I close this issue by now. For further help, please create an new issue with a reference on this one.
